variables:
  TEST_DATABASE_URL: ecto://postgres:postgres@postgres/elixir_formula_test
  SECRET_KEY_BASE: c078289ce7b5462881ab39256b9157c74fa392999f2c816f1fc8a9e64d5215b9
  MIX_ENV: 'test'

stages:
  - init
  - lint
  - test

.elixir_default: &elixir_default
  image: bitwalker/alpine-elixir:1.11.0
  before_script:
    - mix local.hex --force
    - mix local.rebar --force

# Init stage

elixir_compile:
  <<: *elixir_default
  stage: init
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - mix.lock
      - _build
      - deps
  script:
    - apk update
    - apk add alpine-sdk
    - mix deps.get --only test
    - mix compile --warnings-as-errors

# Lint stage

linter:
  <<: *elixir_default
  stage: lint
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - mix.lock
      - _build
      - deps
  script:
    - mix format --check-formatted
    - mix credo --strict

# Test stage

tests:
  <<: *elixir_default
  stage: test
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - mix.lock
      - _build
      - deps
  services:
    - postgres:11.1
  script:
    - mix ecto.setup
    - mix coveralls
